/**
 * Test Parish Parish Page
 *
 * Auto-generated by Qoder workflow on 2026-03-15T09:48:04.442848
 */

import { notFound } from 'next/navigation';
import { resolveParish } from '@/lib/tenant/resolver';
import { getCurrentLiturgicalSeason } from '@/lib/tenant/config';
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Badge,
  Avatar,
  AvatarFallback,
  AvatarImage,
  Separator,
} from '@journeyoflife-org/ui';
import {
  MapPin,
  Phone,
  Mail,
  Clock,
  Calendar,
  Heart,
  User,
  ChevronRight,
  Church,
} from 'lucide-react';

// Skip static generation — test page with dynamic tenant resolution
export const dynamic = 'force-dynamic';

interface ParishPageProps {
  params?: {
    parish?: string;
  };
}

export default async function TestParishParishPage(_props: ParishPageProps): Promise<JSX.Element> {
  // Use default parish for static test page
  const parishSlug = 'holy-cross';
  const parish = await resolveParish(parishSlug);

  if (!parish) {
    notFound();
  }

  const season = getCurrentLiturgicalSeason();

  return (
    <main className="bg-background min-h-screen">
      <div className="container mx-auto px-4 py-12">
        <div className="mb-12 text-center">
          <h1 className="mb-4 text-4xl font-bold">{parish.name}</h1>
          <p className="text-muted-foreground">Test Parish</p>
          <Badge variant="secondary" className="mt-4">
            {season.replace('_', ' ').toUpperCase()}
          </Badge>
        </div>

        <div className="grid gap-8 lg:grid-cols-3">
          <div className="space-y-8 lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle>Welcome</CardTitle>
                <CardDescription>
                  Welcome to Test Parish. We are a Catholic parish serving the faithful in Vilnius.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  This page was auto-generated and should be customized with actual parish
                  information, mass schedules, contact details, and announcements.
                </p>
              </CardContent>
            </Card>
          </div>

          <div className="space-y-6">
            <Card>
              <CardHeader className="pb-4">
                <CardTitle>Quick Links</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button variant="outline" className="w-full justify-between">
                  Mass Schedule <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="outline" className="w-full justify-between">
                  Contact Us <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="outline" className="w-full justify-between">
                  Donate <Heart className="h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </main>
  );
}
