# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='page views')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='unique visitors')),
                ('sessions', models.PositiveIntegerField(default=0, verbose_name='sessions')),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='bounce rate')),
                ('avg_session_duration', models.PositiveIntegerField(default=0, verbose_name='avg session duration (s)')),
                ('new_visitors', models.PositiveIntegerField(default=0, verbose_name='new visitors')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total donations')),
                ('donation_count', models.PositiveIntegerField(default=0, verbose_name='donation count')),
            ],
            options={
                'verbose_name': 'daily stats',
                'verbose_name_plural': 'daily stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=512, verbose_name='page path')),
                ('referrer', models.CharField(blank=True, max_length=512, verbose_name='referrer')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='session ID')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='country code')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='language')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=16, verbose_name='device type')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (s)')),
            ],
            options={
                'verbose_name': 'page view',
                'verbose_name_plural': 'page views',
                'ordering': ['-created_at'],
            },
        ),
    ]
