# Generated by Django 6.0.3 on 2026-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('organizations', '0003_consentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='consent_given',
            field=models.BooleanField(db_index=True, default=False, help_text='GDPR Art. 7: User consented to analytics tracking', verbose_name='consent given'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='consent_version',
            field=models.CharField(blank=True, help_text='Version of consent banner shown to user', max_length=32, verbose_name='consent version'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['organization', 'consent_given'], name='analytics_p_organiz_555e76_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['consent_given', 'created_at'], name='analytics_p_consent_ae6ab9_idx'),
        ),
    ]
