# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='user ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('EXPORT', 'Export')], db_index=True, max_length=16, verbose_name='action')),
                ('entity_type', models.CharField(db_index=True, max_length=128, verbose_name='entity type')),
                ('entity_id', models.CharField(db_index=True, max_length=128, verbose_name='entity ID')),
                ('field_changes', models.JSONField(default=dict, verbose_name='field changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='correlation ID')),
                ('extra', models.JSONField(default=dict, verbose_name='extra data')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['user_id', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
    ]
