# Generated by Django 6.0.3 on 2026-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('EXPORT', 'Export'), ('REFUND', 'Refund'), ('ACCESS', 'Data Access'), ('ERASURE', 'Data Erasure'), ('DSR_ACCESS', 'DSR - Access Request'), ('DSR_RECTIFY', 'DSR - Rectification'), ('DSR_ERASE', 'DSR - Erasure Request'), ('DSR_RESTRICT', 'DSR - Restriction'), ('DSR_PORTABILITY', 'DSR - Data Portability'), ('DSR_OBJECT', 'DSR - Objection'), ('CONSENT_GIVEN', 'Consent Given'), ('CONSENT_WITHDRAWN', 'Consent Withdrawn'), ('LEGAL_HOLD_APPLIED', 'Legal Hold Applied'), ('LEGAL_HOLD_RELEASED', 'Legal Hold Released'), ('DONATION', 'Donation'), ('PAYMENT', 'Payment')], db_index=True, max_length=24, verbose_name='action'),
        ),
    ]
