# Generated by Django 6.0.3 on 2026-04-06
# Adds GDPR compliance fields to AuditLog

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='organization ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='consent_reference',
            field=models.CharField(blank=True, max_length=64, verbose_name='consent reference'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='legal_basis',
            field=models.CharField(blank=True, max_length=32, verbose_name='legal basis'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='data_subject_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='data subject ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='checksum'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization_id', 'created_at'], name='core_audit_organiz_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['data_subject_id', 'action'], name='core_audit_data_su_idx'),
        ),
    ]
