# Generated by Django 6.0.3 on 2026-07-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_gdpr_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_organiz_c79039_idx',
            old_name='core_audit_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_data_su_a7b132_idx',
            old_name='core_audit_data_su_idx',
        ),
    ]
