# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash')], max_length=20, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='transaction ID')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='gateway response')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='donor email')),
                ('donor_name', models.CharField(blank=True, max_length=255, verbose_name='donor name')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonymous')),
                ('is_recurring', models.BooleanField(db_index=True, default=False, verbose_name='recurring')),
                ('frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16, verbose_name='frequency')),
                ('recurring_plan_id', models.CharField(blank=True, max_length=255, verbose_name='recurring plan ID')),
                ('next_charge_at', models.DateTimeField(blank=True, null=True, verbose_name='next charge at')),
                ('gift_aid', models.BooleanField(default=False, verbose_name='gift aid')),
                ('dedicated_to', models.CharField(blank=True, max_length=255, verbose_name='dedicated to')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
