# Generated by Django 6.0.3 on 2026-03-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['organization', 'status'], name='donations_d_organiz_efd7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status'], name='donations_d_donor_i_d5122b_idx'),
        ),
    ]
