# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='ISO code')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('native_name', models.CharField(blank=True, max_length=128, verbose_name='native name')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('default_language', models.CharField(max_length=8, verbose_name='default language')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('gdpr_consent_age', models.PositiveSmallIntegerField(default=16, verbose_name='GDPR consent age')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT rate (%)')),
                ('supervisory_authority', models.CharField(blank=True, max_length=255, verbose_name='data supervisory authority')),
                ('supervisory_authority_url', models.URLField(blank=True, verbose_name='authority URL')),
                ('supported_payment_methods', models.JSONField(default=list, verbose_name='payment methods')),
                ('feature_flags', models.JSONField(default=dict, verbose_name='feature flags')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
