/**
 * Test Parish Parish Layout
 * 
 * Auto-generated by Qoder workflow on 2026-03-15T09:48:13.771021
 */

import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { resolveParish } from '@/lib/tenant/resolver';
import { ParishProvider } from '@/components/tenant/ParishProvider';

interface ParishLayoutProps {
  children: React.ReactNode;
  params: {
    parish: string;
  };
}

export async function generateMetadata(
  props: ParishLayoutProps
): Promise<Metadata> {
  const { params } = props;
  const parish = await resolveParish(params.parish);

  if (!parish) {
    return {
      title: 'Parish Not Found | JOL-HUB',
      description: 'The requested parish could not be found.',
    };
  }

  return {
    title: `${parish.name} | JOL-HUB`,
    description: `Welcome to ${parish.name} - A Catholic parish in Vilnius, LT`,
  };
}

export default async function TestParishLtParishLayout(
  props: ParishLayoutProps
) {
  const { children, params } = props;
  const parish = await resolveParish(params.parish);

  if (!parish) {
    notFound();
  }

  return (
    <ParishProvider parish={parish}>
      {children}
    </ParishProvider>
  );
}
