# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('service', models.CharField(db_index=True, max_length=64, verbose_name='service')),
                ('method', models.CharField(max_length=8, verbose_name='HTTP method')),
                ('url', models.URLField(verbose_name='URL')),
                ('request_payload', models.JSONField(default=dict, verbose_name='request payload')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='response status')),
                ('response_payload', models.JSONField(default=dict, verbose_name='response payload')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('error', models.TextField(blank=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'outbound request',
                'verbose_name_plural': 'outbound requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('source', models.CharField(db_index=True, max_length=64, verbose_name='source')),
                ('event_type', models.CharField(db_index=True, max_length=128, verbose_name='event type')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='idempotency key')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-created_at'],
            },
        ),
    ]
