# Generated by Django 6.0.3 on 2026-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("ignored", "Ignored"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
