// =============================================================================
// JOL-HUB 27 EU Country Configurations
// GDPR Article 44: Data residency by EEA region
// =============================================================================

import type { EEARegion } from '@/types';

export interface CountryConfig {
  code: string;
  name: string;
  localName: string;
  flag: string;
  languages: string[];
  currency: string;
  currencySymbol: string;
  eeaRegion: EEARegion;
  gdprImplemented: boolean;
  dioceses: number;
  flagSvg: string;
}

export const EU_COUNTRIES: CountryConfig[] = [
  {
    code: 'LT',
    name: 'Lithuania',
    localName: 'Lietuva',
    flag: '🇱🇹',
    languages: ['lt'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_BALTIC',
    gdprImplemented: true,
    dioceses: 2,
    flagSvg: '/flags/lt.svg',
  },
  {
    code: 'PL',
    name: 'Poland',
    localName: 'Polska',
    flag: '🇵🇱',
    languages: ['pl'],
    currency: 'PLN',
    currencySymbol: 'zł',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 41,
    flagSvg: '/flags/pl.svg',
  },
  {
    code: 'DE',
    name: 'Germany',
    localName: 'Deutschland',
    flag: '🇩🇪',
    languages: ['de'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 27,
    flagSvg: '/flags/de.svg',
  },
  {
    code: 'FR',
    name: 'France',
    localName: 'France',
    flag: '🇫🇷',
    languages: ['fr'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 93,
    flagSvg: '/flags/fr.svg',
  },
  {
    code: 'IT',
    name: 'Italy',
    localName: 'Italia',
    flag: '🇮🇹',
    languages: ['it'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 225,
    flagSvg: '/flags/it.svg',
  },
  {
    code: 'ES',
    name: 'Spain',
    localName: 'España',
    flag: '🇪🇸',
    languages: ['es', 'ca', 'eu', 'gl'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 70,
    flagSvg: '/flags/es.svg',
  },
  {
    code: 'PT',
    name: 'Portugal',
    localName: 'Portugal',
    flag: '🇵🇹',
    languages: ['pt'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 20,
    flagSvg: '/flags/pt.svg',
  },
  {
    code: 'IE',
    name: 'Ireland',
    localName: 'Éire',
    flag: '🇮🇪',
    languages: ['en', 'ga'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 26,
    flagSvg: '/flags/ie.svg',
  },
  {
    code: 'AT',
    name: 'Austria',
    localName: 'Österreich',
    flag: '🇦🇹',
    languages: ['de'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 9,
    flagSvg: '/flags/at.svg',
  },
  {
    code: 'BE',
    name: 'Belgium',
    localName: 'België',
    flag: '🇧🇪',
    languages: ['nl', 'fr', 'de'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 8,
    flagSvg: '/flags/be.svg',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    localName: 'Nederland',
    flag: '🇳🇱',
    languages: ['nl'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 7,
    flagSvg: '/flags/nl.svg',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    localName: 'Lëtzebuerg',
    flag: '🇱🇺',
    languages: ['lb', 'fr', 'de'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_WESTERN',
    gdprImplemented: true,
    dioceses: 1,
    flagSvg: '/flags/lu.svg',
  },
  {
    code: 'DK',
    name: 'Denmark',
    localName: 'Danmark',
    flag: '🇩🇰',
    languages: ['da'],
    currency: 'DKK',
    currencySymbol: 'kr',
    eeaRegion: 'EU_NORDIC',
    gdprImplemented: true,
    dioceses: 1,
    flagSvg: '/flags/dk.svg',
  },
  {
    code: 'SE',
    name: 'Sweden',
    localName: 'Sverige',
    flag: '🇸🇪',
    languages: ['sv'],
    currency: 'SEK',
    currencySymbol: 'kr',
    eeaRegion: 'EU_NORDIC',
    gdprImplemented: true,
    dioceses: 13,
    flagSvg: '/flags/se.svg',
  },
  {
    code: 'FI',
    name: 'Finland',
    localName: 'Suomi',
    flag: '🇫🇮',
    languages: ['fi', 'sv'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_NORDIC',
    gdprImplemented: true,
    dioceses: 8,
    flagSvg: '/flags/fi.svg',
  },
  {
    code: 'EE',
    name: 'Estonia',
    localName: 'Eesti',
    flag: '🇪🇪',
    languages: ['et'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_BALTIC',
    gdprImplemented: true,
    dioceses: 1,
    flagSvg: '/flags/ee.svg',
  },
  {
    code: 'LV',
    name: 'Latvia',
    localName: 'Latvija',
    flag: '🇱🇻',
    languages: ['lv'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_BALTIC',
    gdprImplemented: true,
    dioceses: 4,
    flagSvg: '/flags/lv.svg',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    localName: 'Česko',
    flag: '🇨🇿',
    languages: ['cs'],
    currency: 'CZK',
    currencySymbol: 'Kč',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 8,
    flagSvg: '/flags/cz.svg',
  },
  {
    code: 'SK',
    name: 'Slovakia',
    localName: 'Slovensko',
    flag: '🇸🇰',
    languages: ['sk'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 8,
    flagSvg: '/flags/sk.svg',
  },
  {
    code: 'HU',
    name: 'Hungary',
    localName: 'Magyarország',
    flag: '🇭🇺',
    languages: ['hu'],
    currency: 'HUF',
    currencySymbol: 'Ft',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 12,
    flagSvg: '/flags/hu.svg',
  },
  {
    code: 'RO',
    name: 'Romania',
    localName: 'România',
    flag: '🇷🇴',
    languages: ['ro'],
    currency: 'RON',
    currencySymbol: 'lei',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 6,
    flagSvg: '/flags/ro.svg',
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    localName: 'България',
    flag: '🇧🇬',
    languages: ['bg'],
    currency: 'BGN',
    currencySymbol: 'лв',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 3,
    flagSvg: '/flags/bg.svg',
  },
  {
    code: 'GR',
    name: 'Greece',
    localName: 'Ελλάδα',
    flag: '🇬🇷',
    languages: ['el'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 9,
    flagSvg: '/flags/gr.svg',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    localName: 'Κύπρος',
    flag: '🇨🇾',
    languages: ['el', 'tr'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 1,
    flagSvg: '/flags/cy.svg',
  },
  {
    code: 'MT',
    name: 'Malta',
    localName: 'Malta',
    flag: '🇲🇹',
    languages: ['mt', 'en'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_SOUTHERN',
    gdprImplemented: true,
    dioceses: 1,
    flagSvg: '/flags/mt.svg',
  },
  {
    code: 'SI',
    name: 'Slovenia',
    localName: 'Slovenija',
    flag: '🇸🇮',
    languages: ['sl'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 2,
    flagSvg: '/flags/si.svg',
  },
  {
    code: 'HR',
    name: 'Croatia',
    localName: 'Hrvatska',
    flag: '🇭🇷',
    languages: ['hr'],
    currency: 'EUR',
    currencySymbol: '€',
    eeaRegion: 'EU_EASTERN',
    gdprImplemented: true,
    dioceses: 5,
    flagSvg: '/flags/hr.svg',
  },
];

export function getCountryByCode(code: string): CountryConfig | undefined {
  return EU_COUNTRIES.find((c) => c.code === code);
}

export function getCountriesByRegion(region: EEARegion): CountryConfig[] {
  return EU_COUNTRIES.filter((c) => c.eeaRegion === region);
}

export function getTotalDioceses(): number {
  return EU_COUNTRIES.reduce((sum, c) => sum + c.dioceses, 0);
}
