# Generated by Django 6.0.3 on 2026-07-21 17:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0004_organization_bitrix24_contact_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_organization_data_classification',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_organization_legal_hold',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_organization_bitrix24_sync_status',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='idx_deal_organization_data_classification',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='idx_deal_organization_legal_hold',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='idx_deal_organization_bitrix24_sync_status',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='crm_auditen_organiz_b863f9_idx',
            old_name='idx_auditentry_organization_event_type_created_at',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='crm_auditen_organiz_ff04e3_idx',
            old_name='idx_auditentry_organization_entity_type_entity_id',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='crm_auditen_sequenc_79c6f8_idx',
            old_name='idx_auditentry_sequence_number',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='crm_auditen_created_807767_idx',
            old_name='idx_auditentry_created_at',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_d7c182_idx',
            old_name='idx_contact_organization_last_name_first_name',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_4a6a71_idx',
            old_name='idx_contact_organization_email',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_96521d_idx',
            old_name='idx_contact_organization_envelope_number',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_organiz_2f4097_idx',
            old_name='idx_contact_organization_is_deceased',
        ),
        migrations.RenameIndex(
            model_name='datasubjectrequest',
            new_name='crm_datasub_organiz_fee35c_idx',
            old_name='idx_datasubjectrequest_organization_status_due_date',
        ),
        migrations.RenameIndex(
            model_name='datasubjectrequest',
            new_name='crm_datasub_request_4fb40f_idx',
            old_name='idx_datasubjectrequest_request_type_status',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='crm_deal_organiz_9e5f32_idx',
            old_name='idx_deal_organization_deal_type_stage',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='crm_deal_organiz_7fcf0e_idx',
            old_name='idx_deal_organization_contact',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='crm_deal_organiz_0231ac_idx',
            old_name='idx_deal_organization_created_at',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='crm_deal_organiz_fe675c_idx',
            old_name='idx_deal_organization_payment_processed_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='Data deletion suspended due to legal requirements', verbose_name='legal hold'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='paid amount'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='previous_hash',
            field=models.CharField(blank=True, help_text='Hash chain for audit integrity', max_length=64, verbose_name='previous hash'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='record_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for tamper detection', max_length=64, verbose_name='record hash'),
        ),
    ]
