# Generated by Django 6.0.3 on 2026-07-21 19:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_contact_idx_contact_organization_data_classification_and_more'),
        ('organizations', '0004_organization_bitrix24_contact_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential (PII)'), ('special_category', 'Special Category (Art. 9)'), ('restricted', 'Restricted (Financial/Health)')], db_index=True, default='confidential', max_length=20, verbose_name='data classification')),
                ('legal_hold', models.BooleanField(db_index=True, default=False, help_text='Data deletion suspended due to legal requirements', verbose_name='legal hold')),
                ('legal_hold_reason', models.TextField(blank=True, verbose_name='legal hold reason')),
                ('legal_hold_until', models.DateTimeField(blank=True, null=True, verbose_name='legal hold until')),
                ('record_hash', models.CharField(blank=True, help_text='SHA-256 hash for tamper detection', max_length=64, verbose_name='record hash')),
                ('previous_hash', models.CharField(blank=True, help_text='Hash chain for audit integrity', max_length=64, verbose_name='previous hash')),
                ('consent_status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('pending', 'Pending'), ('not_required', 'Not Required')], default='pending', max_length=20, verbose_name='consent status')),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='consent granted at')),
                ('consent_withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='consent withdrawn at')),
                ('consent_version', models.CharField(default='1.0', max_length=32, verbose_name='consent version')),
                ('bitrix24_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Bitrix24 ID')),
                ('bitrix24_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitrix24 synced at')),
                ('bitrix24_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=20, verbose_name='Bitrix24 sync status')),
                ('title', models.CharField(help_text='Lead title / subject line', max_length=255, verbose_name='title')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('lead_status', models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('PROCESSED', 'Processed'), ('CONVERTED', 'Converted'), ('JUNK', 'Junk'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20, verbose_name='lead status')),
                ('source', models.CharField(blank=True, choices=[('web', 'Website'), ('bitrix24', 'Bitrix24 CRM'), ('phone', 'Phone Call'), ('email', 'Email Inquiry'), ('referral', 'Referral'), ('social', 'Social Media'), ('event', 'Church Event'), ('other', 'Other')], default='bitrix24', max_length=32, verbose_name='source')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Potential deal value upon conversion', max_digits=12, verbose_name='estimated value')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('comments', models.TextField(blank=True, help_text='Bitrix24 COMMENTS field', verbose_name='comments')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converted at')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='family_id',
            field=models.CharField(blank=True, help_text='Bitrix24 UF_FAMILY_ID — links family members', max_length=64, null=True, verbose_name='family ID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='parish_code',
            field=models.CharField(blank=True, help_text='Bitrix24 UF_PARISH_CODE — parish identifier', max_length=64, null=True, verbose_name='parish code'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'parish_code'], name='crm_contact_organiz_afa55d_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('bitrix24_id', ''), _negated=True), fields=('organization', 'bitrix24_id'), name='unique_contact_bitrix24_per_org'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='crm.contact', verbose_name='converted contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'lead_status'], name='crm_lead_organiz_1756bc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'source'], name='crm_lead_organiz_41de2a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'created_at'], name='crm_lead_organiz_9d83ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'email'], name='crm_lead_organiz_e86ac1_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('bitrix24_id', ''), _negated=True), fields=('organization', 'bitrix24_id'), name='unique_lead_bitrix24_per_org'),
        ),
    ]
