/**
 * Test Parish Parish Page
 * 
 * Auto-generated by Qoder workflow on 2026-03-15T09:52:43.264422
 */

import { notFound } from 'next/navigation';
import { resolveParish } from '@/lib/tenant/resolver';
import { getCurrentLiturgicalSeason } from '@/lib/tenant/config';
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Badge,
  Avatar,
  AvatarFallback,
  AvatarImage,
  Separator,
} from '@jol-hub/ui';
import {
  MapPin,
  Phone,
  Mail,
  Clock,
  Calendar,
  Heart,
  User,
  ChevronRight,
  Church,
} from 'lucide-react';

interface ParishPageProps {
  params: {
    parish: string;
  };
}

export default async function TestParishLt3ParishPage(
  props: ParishPageProps
): Promise<JSX.Element> {
  const { params } = props;
  // Use default parish for static test page
  const parishSlug = params?.parish || 'stjoseph';
  const parish = await resolveParish(parishSlug);

  if (!parish) {
    notFound();
  }

  const season = getCurrentLiturgicalSeason();

  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold mb-4">{parish.name}</h1>
          <p className="text-muted-foreground">Test Parish</p>
          <Badge variant="secondary" className="mt-4">
            {season.replace('_', ' ').toUpperCase()}
          </Badge>
        </div>
        
        <div className="grid gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-8">
            <Card>
              <CardHeader>
                <CardTitle>Welcome</CardTitle>
                <CardDescription>
                  Welcome to Test Parish. We are a Catholic parish serving the faithful in Vilnius.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  This page was auto-generated and should be customized with actual parish information,
                  mass schedules, contact details, and announcements.
                </p>
              </CardContent>
            </Card>
          </div>
          
          <div className="space-y-6">
            <Card>
              <CardHeader className="pb-4">
                <CardTitle>Quick Links</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button variant="outline" className="w-full justify-between">
                  Mass Schedule <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="outline" className="w-full justify-between">
                  Contact Us <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="outline" className="w-full justify-between">
                  Donate <Heart className="h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </main>
  );
}
