# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='file')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=16, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('language', models.CharField(db_index=True, default='en', max_length=8, verbose_name='language')),
                ('template', models.CharField(default='default', max_length=64, verbose_name='template')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='meta keywords')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('extra', models.JSONField(default=dict, verbose_name='extra')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
