# Generated by Django 6.0.3 on 2026-03-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_pages', to='content.mediafile', verbose_name='featured image'),
        ),
        migrations.AddField(
            model_name='page',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.page', verbose_name='parent page'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['organization', 'status', 'language'], name='content_pag_organiz_908db3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('organization', 'slug', 'language')},
        ),
    ]
