# Generated by Django 6.0.3 on 2026-03-05 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('org_type', models.CharField(choices=[('church', 'Church'), ('monastery', 'Monastery'), ('chapel', 'Chapel'), ('shrine', 'Shrine'), ('cathedral', 'Cathedral'), ('parish', 'Parish')], db_index=True, max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('country', models.CharField(db_index=True, max_length=2, verbose_name='country')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='logo')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('address_city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('address_postal_code', models.CharField(blank=True, max_length=16, verbose_name='postal code')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('extra', models.JSONField(default=dict, verbose_name='extra')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
            ],
            options={
                'verbose_name': 'organization member',
                'verbose_name_plural': 'organization members',
                'ordering': ['organization', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('domain', models.CharField(blank=True, max_length=255, unique=True, verbose_name='domain')),
                ('theme', models.CharField(default='default', max_length=64, verbose_name='theme')),
                ('default_language', models.CharField(default='en', max_length=8, verbose_name='default language')),
                ('languages', models.JSONField(default=list, verbose_name='languages')),
                ('ssl_enabled', models.BooleanField(default=True, verbose_name='SSL enabled')),
                ('analytics_id', models.CharField(blank=True, max_length=64, verbose_name='analytics ID')),
                ('custom_css', models.TextField(blank=True, verbose_name='custom CSS')),
                ('settings', models.JSONField(default=dict, verbose_name='settings')),
            ],
            options={
                'verbose_name': 'website',
                'verbose_name_plural': 'websites',
            },
        ),
    ]
