# Generated by Django 6.0.3 on 2026-03-29 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('analytics_consent_enabled', models.BooleanField(default=False, help_text='Organization has enabled analytics tracking with user consent', verbose_name='analytics consent enabled')),
                ('marketing_consent_enabled', models.BooleanField(default=False, help_text='Organization has enabled marketing with user consent', verbose_name='marketing consent enabled')),
                ('functional_consent_enabled', models.BooleanField(default=False, help_text='Organization has enabled functional cookies with user consent', verbose_name='functional consent enabled')),
                ('consent_updated_at', models.DateTimeField(auto_now=True, verbose_name='consent updated at')),
                ('consent_version', models.CharField(default='1.0', help_text='Version of consent policy in effect', max_length=32, verbose_name='consent version')),
                ('privacy_policy_url', models.URLField(blank=True, help_text='URL to organization privacy policy', verbose_name='privacy policy URL')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_settings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'consent settings',
                'verbose_name_plural': 'consent settings',
            },
        ),
    ]
