# Generated by Django 6.0.3 on 2026-07-21 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_consentsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bitrix24_contact_group_id',
            field=models.PositiveIntegerField(blank=True, help_text='Contact group ID in Bitrix24 CRM', null=True, verbose_name='Bitrix24 Contact Group ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bitrix24_portal_id',
            field=models.CharField(blank=True, help_text='Bitrix24 portal domain for CRM integration', max_length=64, verbose_name='Bitrix24 Portal ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bitrix24_webhook_url',
            field=models.TextField(blank=True, help_text='Incoming webhook URL for Bitrix24 API', verbose_name='Bitrix24 Webhook URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='canonical_records',
            field=models.BooleanField(default=False, help_text='Organization maintains sacramental records (Canon 535)', verbose_name='canonical records'),
        ),
        migrations.AddField(
            model_name='organization',
            name='compliance_level',
            field=models.CharField(choices=[('gdpr', 'GDPR Only'), ('soc2_gdpr', 'SOC2 + GDPR'), ('soc2_gdpr_pci', 'SOC2 + GDPR + PCI-DSS'), ('canonical', 'Canon Law + GDPR')], default='gdpr', help_text='Applicable compliance framework', max_length=20, verbose_name='compliance level'),
        ),
        migrations.AddField(
            model_name='organization',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Unique entity identifier (e.g., lt-catholic-basilica-001)', max_length=64, unique=True, verbose_name='entity ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_hold',
            field=models.BooleanField(default=False, help_text='Data deletion suspended due to legal proceedings', verbose_name='legal hold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_hold_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='legal hold applied at'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_hold_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_legal_holds', to=settings.AUTH_USER_MODEL, verbose_name='legal hold applied by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_hold_reason',
            field=models.TextField(blank=True, help_text='Reason for legal hold (e.g., pending litigation, regulatory investigation)', verbose_name='legal hold reason'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_hold_until',
            field=models.DateTimeField(blank=True, help_text='Expiration date of legal hold', null=True, verbose_name='legal hold until'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_diocese',
            field=models.ForeignKey(blank=True, help_text='Parent organization in diocesan hierarchy', limit_choices_to={'org_type__in': ['diocese', 'deanery']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='organizations.organization', verbose_name='parent diocese/deanery'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sacramental_data_processing',
            field=models.BooleanField(default=False, help_text='GDPR Art. 9(2)(d) - Processing for religious purposes', verbose_name='sacramental data processing'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('basilica', 'Basilica'), ('cathedral', 'Cathedral'), ('diocese', 'Diocese'), ('deanery', 'Deanery'), ('church', 'Church'), ('parish', 'Parish'), ('monastery', 'Monastery'), ('chapel', 'Chapel'), ('shrine', 'Shrine'), ('church_protestant', 'Protestant Church'), ('church_orthodox', 'Orthodox Church'), ('church_other', 'Other Christian Church'), ('funeral_service', 'Funeral Service'), ('cemetery_service', 'Cemetery Service')], db_index=True, max_length=20, verbose_name='type'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['compliance_level'], name='organizatio_complia_1b1c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['legal_hold'], name='organizatio_legal_h_e2c6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['entity_id'], name='organizatio_entity__1e19b9_idx'),
        ),
    ]
